from settings.train_settings import BATCH_SIZE

# CONV
# RETRAIN_LR = 2e-4 * (BATCH_SIZE ** 0.5)
# RETRAIN_L2REG = 1e-4
# RETRAIN_RESUME_EPOCH = 1
# RETRAIN_EPOCHS = 30

# FF
RETRAIN_LR = 1e-3 * (BATCH_SIZE ** 0.5)
RETRAIN_L2REG = 1e-4
RETRAIN_RESUME_EPOCH = 1
RETRAIN_EPOCHS = 15
